### ISSUE TITLE
Failed to run the ticketing example

### ISSUE THREAD

**Issue by oscarrodrigues** [vmware-samples/vcd-ext-samples#72] opened 2021-11-20 16:56 UTC
I am trying to develop a plugin for VCD 10.3 using the ticketing example available at https://vmware.github.io/vcd-ext-sdk/docs/development_examples/ticketing/.

I created the project and successfully logged in using vcd-ext but when executing "npm run start" command I received an error message. 

I thought it was some problem with the node (v12.22.7) and npm (6.14.15) versions that I was using. I decided to use the image docker node:12.16.3 with the same versions as the tutorial. I did not succeed. 

```
root@51418060f483:/MyPlugin# npm run start

> MyPlugin@0.0.1 start /MyPlugin
> vcd-ext serve

Loading package with root: /MyPlugin

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! MyPlugin@0.0.1 start: `vcd-ext serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the MyPlugin@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-11-20T15_44_20_540Z-debug.log
```

I decided to download the ticketing example project from github but I also got the same error.
Below are the steps.

1. Versions of node and npm used in image docker node: 12.16.3 
```
root@51418060f483:/# node -v
v12.16.3
root@51418060f483:/# npm -v
6.14.4
```

2. Download the project from github.
```
root@51418060f483:/# git clone https://github.com/vmware-samples/vcd-ext-samples.git -b guide-examples/ticketing ticketing
Cloning into 'ticketing'...
remote: Enumerating objects: 743, done.
remote: Counting objects: 100% (326/326), done.
remote: Compressing objects: 100% (251/251), done.
remote: Total 743 (delta 133), reused 179 (delta 56), pack-reused 417
Receiving objects: 100% (743/743), 837.66 KiB | 0 bytes/s, done.
Resolving deltas: 100% (294/294), done.
```

3. Successfully running "npm install".
```
root@51418060f483:/ticketing/ticketing# npm install
> core-js@3.6.4 postinstall /ticketing/ticketing/node_modules/@angular-devkit/build-angular/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"
...
```

4. Successfully running "npm run bootstrap".
```
root@51418060f483:/ticketing/ticketing# npm run bootstrap
> ticketing@0.0.1 bootstrap /ticketing/ticketing
> lerna bootstrap

lerna notice cli v3.22.1
lerna info Bootstrapping 2 packages
lerna info Installing external dependencies
lerna info Symlinking packages and binaries
lerna success Bootstrapped 2 packages
```

5. Successfully running "npm run build".
```
root@51418060f483:/ticketing/ticketing# npm run build

> ticketing@0.0.1 build /ticketing/ticketing
> lerna run build

lerna notice cli v3.22.1
lerna info Executing command in 2 packages: "npm run build"
lerna info run Ran npm script 'build' in 'ticketing-types' in 5.6s:

> ticketing-types@0.0.1 build /ticketing/ticketing/packages/types
> vcd-ext build --only=types

Loading package with root: /ticketing/ticketing
Running build for plugin @vcd/care-package-plugin-types/TypesCarePackagePlugin with elements types
Writing file: types/Ticket.json
lerna info run Ran npm script 'build' in 'uiPlugin' in 16.3s:

> uiPlugin@0.0.1 build /ticketing/ticketing/packages/uiPlugin
> ng build


chunk {0} bundle.js (main) 658 kB [entry] [rendered]
Date: 2021-11-20T16:41:46.446Z - Hash: a973788f6ab61053aa72 - Time: 12704ms
lerna success run Ran npm script 'build' in 2 packages in 21.9s:
lerna success - ticketing-types
lerna success - uiPlugin
```

6. Successfully creating a login session with vcd-ext. Successfully created /root/.vcd/config file. 

```
$ vcd-ext login userAliasName https://********.com/cloudapi userteste@VdcTeste ********

$ cat /root/.vcd/config 
{"userAliasName":{"basePath":"https://********.com/cloudapi","authorized":true,"username":"userteste","org":"VdcTeste","authorizationKey":"eyJhbGciOiJSUzI1NiJ9.e...rHqs2pdYSv7ZBta4yLg"},"current":"userAliasName"}
```

7. Running the plugin in an emulator. Failed.
```
root@51418060f483:/ticketing/ticketing# npm run start

> ticketing@0.0.1 start /ticketing/ticketing
> vcd-ext serve

Loading package with root: /ticketing/ticketing

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ticketing@0.0.1 start: `vcd-ext serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ticketing@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-11-20T16_47_50_856Z-debug.log
```

8. Logs
```
root@51418060f483:/ticketing/ticketing# cat  /root/.npm/_logs/2021-11-20T16_47_50_856Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'start' ]
2 info using npm@6.14.4
3 info using node@v12.16.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle ticketing@0.0.1~prestart: ticketing@0.0.1
6 info lifecycle ticketing@0.0.1~start: ticketing@0.0.1
7 verbose lifecycle ticketing@0.0.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle ticketing@0.0.1~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/ticketing/ticketing/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle ticketing@0.0.1~start: CWD: /ticketing/ticketing
10 silly lifecycle ticketing@0.0.1~start: Args: [ '-c', 'vcd-ext serve' ]
11 silly lifecycle ticketing@0.0.1~start: Returned: code: 1  signal: null
12 info lifecycle ticketing@0.0.1~start: Failed to exec start script
13 verbose stack Error: ticketing@0.0.1 start: `vcd-ext serve`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:310:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:310:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid ticketing@0.0.1
15 verbose cwd /ticketing/ticketing
16 verbose Linux 5.14.12-200.fc34.x86_64
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
18 verbose node v12.16.3
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error ticketing@0.0.1 start: `vcd-ext serve`
22 error Exit status 1
23 error Failed at the ticketing@0.0.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by nvladimirovi** [comment] 2022-02-14 11:30
Can you please use https://github.com/nvm-sh/nvm, in the case of docker we can't be sure what the issue is, the exception is generic.

**Comment by nvladimirovi** [comment] 2022-03-07 14:10
Closing the issue, I tried to start the ticketing and it works when using nvm. Feel free to re-open.

**Closed by nvladimirovi** 2022-03-07 14:10 UTC
